### ISSUE TITLE
Coding style ebuild

### ISSUE THREAD

**Issue by ghost** [christgau/wsdd-gentoo#1]
Hi,

I think that the gentoo maintainers prefer to use the python eclass for handling installing python scripts. This is the feedback I got from irc://#gentoo-dev-help with a link to https://wiki.gentoo.org/wiki/Project:Python/python-utils-r1 I think the reason is to be compatible with eslect-python and python-wrapper that gentoo uses. `python_foreach_impl python_newscript src/wsdd.py wsdd` fixes all the links etc to make this work.

Also, do we need samba to start and run wsdd? Perhaps change to `use samba` instead of `need samba`? Of course, the usefulness can be questioned 😃

**Comment by christgau** [comment]
Hi,
> I think that the gentoo maintainers prefer to use the python eclass for handling installing python scripts. This is the feedback I got from irc://#gentoo-dev-help with a link to https://wiki.gentoo.org/wiki/Project:Python/python-utils-r1 I think the reason is to be compatible with eslect-python and python-wrapper that gentoo uses. `python_foreach_impl python_newscript src/wsdd.py wsdd` fixes all the links etc to make this work.

[I considered using python-utils as well](https://github.com/christgau/wsdd-gentoo/blob/7002134/net-misc/wsdd/wsdd-0.3.ebuild#L24), but `newbin` worked quite well for my first ebuild 😉 Nevertheless, I think, the python-utils are more appropriate here. Thanks for pointing that out

> Also, do we need samba to start and run wsdd? Perhaps change to `use samba` instead of `need samba`? Of course, the usefulness can be questioned 😃

I guess, this refers to the init.d script. I thinks it is a good idea to depend on a (running) Samba server, if such one is installed. Note that this is not the default behavior. It is only enabled, if the `samba` use flag has been provided during emerge. If that one is missing, [the dependency is removed](https://github.com/christgau/wsdd-gentoo/blob/7002134/net-misc/wsdd/wsdd-0.3.ebuild#L32) from the init script when the package is installed.

**Comment by christgau** [comment]
I [improved the ebuild](https://github.com/christgau/wsdd-gentoo/commit/3e273c45df802bb4ebe6ecfee4cb7c74c7b7db61#diff-8d601145e6c4765d71ebb23dc5d978f6) file a little by using the `python-r1` eclass. I also [added a metadata.xml](https://github.com/christgau/wsdd-gentoo/commit/29e5ce48f0495a3d894f3791f39029f3b31cc6b7). Both may be worth a look and feedback  ;-)

**Comment by ghost** [comment]
Great :)

Haven't had time to test yet, but do the init.d scripts get installed without  `doinitd` and `systemd_dounit`?

**Comment by christgau** [comment]
> Haven't had time to test yet, but do the init.d scripts get installed without `doinitd` and `systemd_dounit`?

No they won't, but there is a `doinitd` in the current version. Systemd support is missing.

**Comment by christgau** [comment]
Closing this issue. The currently implemented ebuilds include python-utils-r1 eclass and others. When wsdd v0.4 and the ebuilds are passed to the proxy maintainers we'll see what can be improved.
